### ISSUE TITLE
not available for sublime text 3?

### ISSUE THREAD

**Issue by maxheld83** [Nucc/Thesaurus#2]
It seems like I can't install this (great!) package on sublime text 3. My mistake or is that a missing feature?
I'd love to use your package.

**Comment by Nucc** [comment]
hey,

I haven't tried sublime text 3 yet but I'll check it.

**Comment by paulogaspar** [comment]
Not working in sublime 3 (windows) here...

**Comment by Nucc** [comment]
Ok, I'll check it.

**Comment by cazacugmihai** [comment]
Can you make it to work with s3, please? 
Thanks!

**Comment by Nucc** [comment]
Oh yeah, sorry, I spent some time on it, but my problem was I couldn't install Sublime 3 to my system (OSX Snow Leopard). Now I have a new macbook with Maverick, so I'll check it as soon as I have some time...

**Comment by cazacugmihai** [comment]
Thank you! :)

**Comment by git-commit** [comment]
Any news on this? If you're not working on it I'll go ahead and make an ST3 fork.

Is there a way to make the code both ST2 and ST3 compatible?

Also I would need support for other languages, especially german.

**Comment by Nucc** [comment]
Hi, no sorry, I haven't worked on it. Go for it.

**Comment by git-commit** [comment]
I have never worked with a project that needs to be compatible with python2 and python3 at the same time.
Any ideas on how to keep the code both ST2 and ST3 compatible to merge it back later?

**Comment by gmalone** [comment]
Would love it if Thesaurus would *replace* the selected word.  Using version dl'd 2018.09.15

**Comment by Nucc** [comment]
I have no time working on it but please open a new issue and I hope someone will pick it up.
